#!/usr/bin/env bash
# Copyright (C) 2014 Igor Kushnir <igorkuo AT Google mail>
# License: GPL v3+ (http://www.gnu.org/copyleft/gpl.html)
# update_and_configure_submodules: inits and updates Venturous git submodules;
# gets necessary png icons; configures build.

set -e

print_help()
{
    echo 'This script accepts following options:
        "download-png", "generate-png", "qt4", "qt5", "help", "--".'
    echo '"download-png" and "qt4" are assumed if not specified.'
    echo 'Options that appear later override preceding ones.'
    echo 'Options after "--" are ignored.'
    echo 'Option may be prefixed with "--" (GNU-style long-options) or not, your choice.'
    exit 1
}

matches()
{
    [[ ("$1" == "$2") || ("$1" == "--$2") ]]
}

generate_png=false
qt4=true
for arg in "$@"
do
    if matches "$arg" "download-png" ; then
        generate_png=false
    elif matches "$arg" "generate-png" ; then
        generate_png=true
    elif matches "$arg" "qt4" ; then
        qt4=true
    elif matches "$arg" "qt5" ; then
        qt4=false
    elif matches "$arg" "help" ; then
        print_help
    elif [[ "$arg" == "--" ]] ; then
        break
    else
        echo "Unrecognized option: $1"
        print_help
    fi
done

git submodule init
git submodule update

cd modules/vedgTools/QtXmlUtilities
git submodule init TemplateUtilities
git submodule update TemplateUtilities

cd ../../..
script_path="resources/SimpleFugue"
if [[ "$generate_png" == true ]] ; then
    "$script_path/generate_png"
else
    "$script_path/download_png"
fi

dir_name=build
mkdir -p $dir_name
cd $dir_name

if [[ "$qt4" == true ]] ; then
    args="-DFORCE_QT4=ON"
else
    args="-DFORCE_QT4=OFF"
fi
cmake "$args" -DCMAKE_BUILD_TYPE=Release ..

echo ''
echo 'Default configuration is complete. Follow instructions below to install Venturous:'
echo '1. Enter build directory (type "cd build").'
echo '2. If you wish to change default configuration, type "cmake -i .." (when asked "Would you like to see advanced options? [No]:", just hit <Enter>).'
echo '   Alternatively, if you have cmake-gui installed, you could type "cmake-gui .".'
echo '   If you are happy with default configuration, skip this step.'
echo '3. After you are done configuring (or skipped configuration step) type "make -j 2" (you can replace "2" with the number of processor cores to speed up build process).'
echo '4. Acquire root privileges ("sudo" or "su") and type "make install" to install Venturous.'
